In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re
import nltk  
#nltk.download('stopwords') 
from nltk.corpus import stopwords  
from nltk.stem.porter import PorterStemmer 
stop_word=stopwords.words('english')

In [2]:
tem=pd.read_csv("Tweets.csv")

In [3]:
tem

textID                                               text  \
0      cb774db0d1                I`d have responded, if I were going   
1      549e992a42      Sooo SAD I will miss you here in San Diego!!!   
2      088c60f138                          my boss is bullying me...   
3      9642c003ef                     what interview! leave me alone   
4      358bd9e861   Sons of ****, why couldn`t they put them on t...   
...           ...                                                ...   
27476  4eac33d1c0   wish we could come see u on Denver  husband l...   
27477  4f4c4fc327   I`ve wondered about rake to.  The client has ...   
27478  f67aae2310   Yay good for both of you. Enjoy the break - y...   
27479  ed167662a5                         But it was worth it  ****.   
27480  6f7127d9d7     All this flirting going on - The ATG smiles...   

                                           selected_text sentiment  
0                    I`d have responded, if I were going   neutral  
1                                               Sooo SAD  negative  
2                                            bullying me  negative  
3                                         leave me alone  negative  
4                                          Sons of ****,  negative  
...                                                  ...       ...  
27476                                             d lost  negative  
27477                                      , don`t force  negative  
27478                          Yay good for both of you.  positive  
27479                         But it was worth it  ****.  positive  
27480  All this flirting going on - The ATG smiles. Y...   neutral  

[27481 rows x 4 columns]

In [4]:
tem.drop(["textID",'text'],axis=1,inplace=True)

In [5]:
tem.head()

selected_text sentiment
0  I`d have responded, if I were going   neutral
1                             Sooo SAD  negative
2                          bullying me  negative
3                       leave me alone  negative
4                        Sons of ****,  negative

In [6]:
tem.rename(columns = {'selected_text':'text'}, inplace = True)

In [7]:
tem.head()

text sentiment
0  I`d have responded, if I were going   neutral
1                             Sooo SAD  negative
2                          bullying me  negative
3                       leave me alone  negative
4                        Sons of ****,  negative

In [8]:
tem.text.dtypes

dtype('O')

In [9]:
tem['text']=(tem['text'].astype('str'))

In [10]:
tem.text.dtypes

dtype('O')

In [11]:
tem.text=tem.text.apply( lambda x: re.sub("[^a-zA-Z ]", "",x))

In [12]:
tem

text sentiment
0                      Id have responded if I were going   neutral
1                                               Sooo SAD  negative
2                                            bullying me  negative
3                                         leave me alone  negative
4                                               Sons of   negative
...                                                  ...       ...
27476                                             d lost  negative
27477                                         dont force  negative
27478                           Yay good for both of you  positive
27479                              But it was worth it    positive
27480  All this flirting going on  The ATG smiles Yay...   neutral

[27481 rows x 2 columns]

In [13]:
tem.duplicated().sum()

5820

In [14]:
tem.drop_duplicates(inplace=True)

In [15]:
tem.duplicated().sum()

0

In [16]:
tem.isna().sum()

text         0
sentiment    0
dtype: int64

In [17]:
tem['sentiment'].value_counts()

neutral     11096
negative     5469
positive     5096
Name: sentiment, dtype: int64

In [18]:
tem['sentiment'].unique()

array(['neutral', 'negative', 'positive'], dtype=object)

In [19]:
from sklearn import preprocessing

In [20]:
le=preprocessing.LabelEncoder()

In [21]:
tem['sentiment']=le.fit_transform(tem['sentiment'])

In [22]:
tem['sentiment'].unique()

array([1, 0, 2])

In [23]:
tem

text  sentiment
0                      Id have responded if I were going          1
1                                               Sooo SAD          0
2                                            bullying me          0
3                                         leave me alone          0
4                                               Sons of           0
...                                                  ...        ...
27476                                             d lost          0
27477                                         dont force          0
27478                           Yay good for both of you          2
27479                              But it was worth it            2
27480  All this flirting going on  The ATG smiles Yay...          1

[21661 rows x 2 columns]

In [24]:
tem.text=tem.text.apply(lambda x: x.lower())

In [25]:
tem.head()

text  sentiment
0  id have responded if i were going          1
1                           sooo sad          0
2                        bullying me          0
3                     leave me alone          0
4                           sons of           0

In [26]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [27]:
tem.text=tem.text.apply(lambda x: x.split())

In [28]:
tem['text']

0                [id, have, responded, if, i, were, going]
1                                              [sooo, sad]
2                                           [bullying, me]
3                                       [leave, me, alone]
4                                               [sons, of]
                               ...                        
27476                                            [d, lost]
27477                                        [dont, force]
27478                      [yay, good, for, both, of, you]
27479                            [but, it, was, worth, it]
27480    [all, this, flirting, going, on, the, atg, smi...
Name: text, Length: 21661, dtype: object

In [29]:
tem.head()

text  sentiment
0  [id, have, responded, if, i, were, going]          1
1                                [sooo, sad]          0
2                             [bullying, me]          0
3                         [leave, me, alone]          0
4                                 [sons, of]          0

In [30]:
tem.text=tem.text.apply(lambda x: [word for word in x if word not in set(stopwords.words('english'))])

In [31]:
tem.head()

text  sentiment
0  [id, responded, going]          1
1             [sooo, sad]          0
2              [bullying]          0
3          [leave, alone]          0
4                  [sons]          0

In [32]:
ps=PorterStemmer()

In [33]:
tem.text=tem.text.apply(lambda x:[ps.stem(word) for word in x])

In [34]:
tem.head()

text  sentiment
0  [id, respond, go]          1
1        [sooo, sad]          0
2            [bulli]          0
3       [leav, alon]          0
4              [son]          0

In [35]:
tem.text=tem.text.apply(lambda x: " ".join(x))

In [36]:
tem.head()

text  sentiment
0  id respond go          1
1       sooo sad          0
2          bulli          0
3      leav alon          0
4            son          0

In [37]:
tem2=pd.read_csv("Tweets.csv")

In [38]:
def preprocess(x):
    x=re.sub("[^a-zA-Z ]", "",x)
    x=x.lower()
    x=x.split()  
    x=[word  for word in x if word not in set(stopwords.words('english'))]  
    x=[ps.stem(word) for word in x] 
    x=" ".join(x)
    return x

In [39]:
tem2.head()

textID                                               text  \
0  cb774db0d1                I`d have responded, if I were going   
1  549e992a42      Sooo SAD I will miss you here in San Diego!!!   
2  088c60f138                          my boss is bullying me...   
3  9642c003ef                     what interview! leave me alone   
4  358bd9e861   Sons of ****, why couldn`t they put them on t...   

                         selected_text sentiment  
0  I`d have responded, if I were going   neutral  
1                             Sooo SAD  negative  
2                          bullying me  negative  
3                       leave me alone  negative  
4                        Sons of ****,  negative

In [40]:
tem2.drop(["textID",'text'],axis=1,inplace=True)

In [41]:
tem2.drop_duplicates(inplace=True)

In [42]:
tem2['sentiment']=le.fit_transform(tem2['sentiment'])

In [43]:
tem2.head()

selected_text  sentiment
0  I`d have responded, if I were going          1
1                             Sooo SAD          0
2                          bullying me          0
3                       leave me alone          0
4                        Sons of ****,          0

In [44]:
tem2['selected_text'].dtypes

dtype('O')

In [45]:
tem2['selected_text']=(tem2['selected_text'].astype('str'))

In [46]:
tem2['selected_text'].dtypes

dtype('O')

In [47]:
tem2['selected_text']=tem2['selected_text'].apply(preprocess)

In [48]:
tem2

selected_text  sentiment
0                   id respond go          1
1                        sooo sad          0
2                           bulli          0
3                       leav alon          0
4                             son          0
...                           ...        ...
27476                        lost          0
27477                   dont forc          0
27478                    yay good          2
27479                       worth          2
27480  flirt go atg smile yay hug          1

[22510 rows x 2 columns]

In [49]:
from sklearn.feature_extraction.text import CountVectorizer

In [51]:
cv=CountVectorizer(analyzer='word',ngram_range=(1,1))

In [52]:
x= tem.text
y=tem.sentiment

In [53]:
x

0                     id respond go
1                          sooo sad
2                             bulli
3                         leav alon
4                               son
                    ...            
27476                          lost
27477                     dont forc
27478                      yay good
27479                         worth
27480    flirt go atg smile yay hug
Name: text, Length: 21661, dtype: object

In [54]:
x=cv.fit_transform(x)

In [55]:
cv.get_feature_names_out()

array(['aa', 'aaa', 'aaaa', ..., 'zwart', 'zwitschert', 'zzzz'],
      dtype=object)

In [56]:
print(x.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [57]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier # Import Decision Tree Classifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split,cross_val_score # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

In [58]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [59]:
log=LogisticRegression(max_iter=1000)
log.fit(x_train,y_train)
log_pred=log.predict(x_test)

In [60]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,confusion_matrix,recall_score,roc_auc_score
from sklearn.metrics import f1_score,precision_recall_curve,roc_curve,ConfusionMatrixDisplay

In [61]:
log_score=accuracy_score(y_test,log_pred)

In [62]:
log_score

0.7539621480227727

In [63]:
print(log_pred)

[1 2 1 ... 2 2 0]


In [64]:
print(y_test)

20813    1
5540     0
26968    1
16553    2
19239    2
        ..
13952    1
16969    1
13888    2
24609    2
1008     0
Name: sentiment, Length: 6499, dtype: int32


In [65]:
data = pd.DataFrame({'Actual': y_test, 'Predicted' : log_pred})
data.sample(20)

Actual  Predicted
21384       1          0
2520        0          0
17557       1          1
20765       2          2
22490       1          1
26403       1          1
23259       0          0
18718       0          0
20613       2          2
6030        2          2
7523        1          0
7990        1          1
4310        1          0
22941       2          2
18501       2          2
16569       1          2
255         1          1
2492        2          0
18317       1          1
9815        2          1

In [66]:
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
rf_pred=rf.predict(x_test)
rf_score=accuracy_score(y_test,rf_pred)

In [67]:
rf_score

0.7062625019233728

In [68]:
data1 = pd.DataFrame({'Actual': y_test, 'Predicted' : rf_pred})
data1.sample(20)

Actual  Predicted
112         2          2
9477        1          1
11035       1          1
23334       1          1
10495       2          2
18931       1          1
5756        1          1
9296        1          0
7252        2          2
24641       1          1
6116        1          2
3404        0          1
11669       0          0
23015       1          1
1012        2          2
1360        2          2
26240       0          0
24927       0          0
26842       1          1
7994        1          1